export const MOCK_POPULARS = [
  {
    adult: false,
    backdrop_path: "/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    genre_ids: [10759, 9648, 18],
    id: 93405,
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    popularity: 1329.39,
    poster_path: "/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
    first_air_date: "2021-09-17",
    name: "Squid Game",
    vote_average: 7.865,
    vote_count: 16236,
  },
];

export const MOCK_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/bKxiLRPVWe2nZXCzt6JPr5HNWYm.jpg",
    id: 110316,
    name: "Alice in Borderland",
    original_name: "今際の国のアリス",
    overview:
      "With his two friends, a video-game-obsessed young man finds himself in a strange version of Tokyo where they must compete in dangerous games to win.",
    poster_path: "/Ac8ruycRXzgcsndTZFK6ouGA0FA.jpg",
    media_type: "tv",
    original_language: "ja",
    genre_ids: [9648, 18, 10759],
    popularity: 91.9987,
    first_air_date: "2020-12-10",
    vote_average: 8.161,
    vote_count: 2262,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/lyZmMTwpr6ZCXKA7lszpXcDwNOM.jpg",
    id: 90462,
    name: "Chucky",
    original_name: "Chucky",
    overview:
      "After a vintage Chucky doll turns up at a suburban yard sale, an idyllic American town is thrown into chaos as a series of horrifying murders begin to expose the town’s hypocrisies and secrets. Meanwhile, the arrival of enemies — and allies — from Chucky’s past threatens to expose the truth behind the killings, as well as the demon doll’s untold origins.",
    poster_path: "/sdCJbGkvnIsIKLxaFQrviriODVq.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [80, 35, 9648],
    popularity: 42.9631,
    first_air_date: "2021-10-12",
    vote_average: 7.837,
    vote_count: 4100,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/yYpQV25I7XB6S0POJOScPjxYWV5.jpg",
    id: 60572,
    name: "Pokémon",
    original_name: "ポケットモンスター",
    overview:
      "Join Ash accompanied by his partner Pikachu, as he travels through many regions, meets new friends and faces new challenges on his quest to become a Pokémon Master.",
    poster_path: "/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg",
    media_type: "tv",
    original_language: "ja",
    genre_ids: [16, 10759, 10765],
    popularity: 358.9492,
    first_air_date: "1997-04-01",
    vote_average: 7.927,
    vote_count: 1984,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg",
    id: 88329,
    name: "Hawkeye",
    original_name: "Hawkeye",
    overview:
      "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero. The two are forced to work together when a presence from Barton’s past threatens to derail far more than the festive spirit.",
    poster_path: "/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [18, 35, 10759],
    popularity: 35.3367,
    first_air_date: "2021-11-24",
    vote_average: 7.835,
    vote_count: 3493,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/u23G9KZregWHs1use6ir1fX27gl.jpg",
    id: 81356,
    name: "Sex Education",
    original_name: "Sex Education",
    overview:
      "Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.",
    poster_path: "/bc3bmTdnoKcRuO9xdQKgAbB7Y9Z.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [35, 18],
    popularity: 91.4332,
    first_air_date: "2019-01-11",
    vote_average: 8.235,
    vote_count: 7523,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/wQEW3xLrQAThu1GvqpsKQyejrYS.jpg",
    id: 94605,
    name: "Arcane",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [16, 10765, 18, 10759],
    popularity: 68.9651,
    first_air_date: "2021-11-06",
    vote_average: 8.764,
    vote_count: 5219,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/q74hFjNMjlA4Fj8mYA42X9lOvLV.jpg",
    id: 99966,
    name: "All of Us Are Dead",
    original_name: "지금 우리 학교는",
    overview:
      "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out — or turn into one of the rabid infected.",
    poster_path: "/pTEFqAjLd5YTsMD6NSUxV6Dq7A6.jpg",
    media_type: "tv",
    original_language: "ko",
    genre_ids: [10759, 18, 10765],
    popularity: 72.4988,
    first_air_date: "2022-01-28",
    vote_average: 8.3,
    vote_count: 4090,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    id: 71446,
    name: "Money Heist",
    original_name: "La casa de papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    media_type: "tv",
    original_language: "es",
    genre_ids: [80, 18],
    popularity: 58.7711,
    first_air_date: "2017-05-02",
    vote_average: 8.2,
    vote_count: 18963,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: "/h0CQ36rm9cSLznve5ocCDtYlnwN.jpg",
    id: 195670,
    name: "XO, Kitty",
    original_name: "XO, Kitty",
    overview:
      "Teen matchmaker Kitty Song Covey thinks she knows everything there is to know about love. But when she moves halfway across the world to reunite with her long-distance boyfriend, she'll soon realize that relationships are a lot more complicated when it's your own heart on the line.",
    poster_path: "/hxvTdKAwv27PUfpXOQp6AwWr6V.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [35, 18],
    popularity: 41.9038,
    first_air_date: "2023-05-18",
    vote_average: 8.092,
    vote_count: 526,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/jnzoh5qoxRLFRIQAxnl6D3RStPC.jpg",
    id: 91363,
    name: "What If...?",
    original_name: "What If...?",
    overview:
      "Taking inspiration from the comic books of the same name, each episode of this animated anthology series questions, revisits and twists classic Marvel Cinematic moments.",
    poster_path: "/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [16, 10759, 10765],
    popularity: 60.1692,
    first_air_date: "2021-08-11",
    vote_average: 8.094,
    vote_count: 4398,
    origin_country: ["US"],
  },
];
